"""Added initial table

Revision ID: ab21609ac088
Revises: 
Create Date: 2022-05-31 10:18:41.294672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab21609ac088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('dt_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('password')
    )
    op.create_table('project',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('user', postgresql.UUID(), nullable=True),
    sa.Column('codename', sa.String(length=50), nullable=False),
    sa.Column('creator_name', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=50), nullable=False),
    sa.Column('client_email', sa.String(length=64), nullable=True),
    sa.Column('client_number', sa.Integer(), nullable=True),
    sa.Column('estimated_worth', sa.Integer(), nullable=True),
    sa.Column('final_worth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('IDR', sa.BigInteger(), nullable=False),
    sa.Column('IDP', sa.BigInteger(), nullable=False),
    sa.Column('PGD', sa.BigInteger(), nullable=False),
    sa.Column('PZI', sa.BigInteger(), nullable=False),
    sa.Column('PIO', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['IDP'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['IDR'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['PGD'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['PIO'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['PZI'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_email'),
    sa.UniqueConstraint('codename')
    )
    op.create_index(op.f('ix_project_IDP'), 'project', ['IDP'], unique=False)
    op.create_index(op.f('ix_project_IDR'), 'project', ['IDR'], unique=False)
    op.create_index(op.f('ix_project_PGD'), 'project', ['PGD'], unique=False)
    op.create_index(op.f('ix_project_PIO'), 'project', ['PIO'], unique=False)
    op.create_index(op.f('ix_project_PZI'), 'project', ['PZI'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_PZI'), table_name='project')
    op.drop_index(op.f('ix_project_PIO'), table_name='project')
    op.drop_index(op.f('ix_project_PGD'), table_name='project')
    op.drop_index(op.f('ix_project_IDR'), table_name='project')
    op.drop_index(op.f('ix_project_IDP'), table_name='project')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('phases')
    # ### end Alembic commands ###
